# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-WSDL-Writer
version:      0.02
version_from: lib/Pod/WSDL/Writer.pm
installdirs:  site
requires:
    Pod::WSDL::Utils:              0.01
    XML::Writer:                   0.531

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
